name: "workflow backend"

on:
    push:
        branches:
            - main

jobs:
    code_analysis_job:
        runs-on: ubuntu-latest
        steps:
            - name: "checkout repository"
              uses: actions/checkout@v2

            - name: "install dependencies"
              run: npm install

            - name: "run code analysis"
              run: npm run lint
    
    unit_testing_job:
        runs-on: ubuntu-latest
        steps:
            - name: "checkout repository"
              uses: actions/checkout@v2

            - name: "install dependencies"
              run: npm install

            - name: "run code quality tests"
              run: npm run test

    build_and_push:
        runs-on: ubuntu-latest
        needs: [ "unit_testing_job", "code_analysis_job" ]
        steps:
            - name: "checkout repository"
              uses: actions/checkout@v2

            - name: "build Docker image"
              run: docker build -t talel12/e-commerce-back .

            - name: "list docker images"
              run: docker images
    # deployment